### ISSUE TITLE
Encoding of strings

### ISSUE THREAD

**Issue by mscheltienne** [mscheltienne/antio#34]
ANT support shared with me a file which had the string `µV` set for channel unit, encoded as `latin1`. This file could thus not be loaded when python tried to decode the string as UTF-8.

The question is, what encoding is the CNT format actually using? Is it using only one encoding or can some fields be encoded with X or Y. I asked ANT's support to look into it, let's see..

**Comment by larsoner** [comment]
If they don't get back to you or if it varies we can add an `encoding="latin-1"` (or "utf-8") argument. I think we've had to do this for other readers before

**Comment by mscheltienne** [comment]
Yes, that's the plan.

**Comment by mscheltienne** [comment]
Response from ANT:

```
The encoding of the string comes from the attribute "UnmanagedType.LPStr UnmanagedType.LPStr" for MarshalAs in the .Net package that results in "A pointer to a null-terminated array of ANSI characters". You can find about this over the following link: https://learn.microsoft.com/en-us/dotnet/framework/interop/default-marshalling-for-strings#strings-used-in-interfaces . ANSI encoding depends on the system’s code page, which is typically a single-byte encoding (e.g., Windows-1252 on Western systems). It does not support full Unicode character sets. This means the data stored in UnmanagedType.LPStr will not be in latin1 or UTF-16 encoding. Instead, it will be in a system-dependent ANSI encoding.
```

I asked if they are storing the system's code page somewhere in the file; else we are left we guess work to do. Maybe `cchardet` could help + an `encoding=...` argument in the API.
